# Generated by Django 4.1.6 on 2023-02-08 11:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="options",
            field=models.IntegerField(
                choices=[(1, "Super admin"), (2, "Admin"), (3, "user")], default=3
            ),
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_number",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-zA-Z]*$", "Only use alphanumeric characters"
                            )
                        ],
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("Two", "Two wheeler"),
                            ("Three", "Three wheeler"),
                            ("Four", "Four wheeler"),
                        ],
                        max_length=5,
                    ),
                ),
                ("vehicle_model", models.CharField(max_length=100)),
                ("vehicle_description", models.TextField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
