# Generated by Django 4.1.6 on 2023-02-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0003_alter_users_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_description",
            field=models.CharField(max_length=200),
        ),
    ]
